In [1]:
import pandas as pd
import numpy as np

### 设置路径

In [2]:
path_pre = '../../'
path_intermediate_dataset = path_pre + 'intermediate-dataset/'
path_modeling_dataset = path_pre + 'modeling-dataset/'

### 加载数据集

In [3]:
dataset = pd.read_hdf(path_intermediate_dataset + 'dataset.h5')
dataset.head()

,label,sitesetID,positionType,connectionType,telecomsOperator,hour,hour_weight,age,gender,education,...,haveBaby,hometown,residence,user_activity,cat_pref,advertiserID,appPlatform,appCategory,app_popularity,is_pref_cat
0,0,0,3,1,1,0,225349,3,2,1,...,1,0,0,2.0,301.0,10,1,108,2.0,False
1,0,0,3,0,2,0,225349,3,2,2,...,1,13,0,2.0,407.0,10,1,108,2.0,False
2,0,0,3,0,3,0,225349,4,2,0,...,5,0,0,5.0,0.0,10,1,108,2.0,False
3,0,0,3,1,1,0,225349,3,1,1,...,0,0,0,2.0,104.0,10,1,108,2.0,False
4,0,0,3,1,1,0,225349,3,1,0,...,0,13,0,5.0,0.0,10,1,108,2.0,False

In [4]:
print(dataset.columns.tolist())

['label', 'sitesetID', 'positionType', 'connectionType', 'telecomsOperator', 'hour', 'hour_weight', 'age', 'gender', 'education', 'marriageStatus', 'haveBaby', 'hometown', 'residence', 'user_activity', 'cat_pref', 'advertiserID', 'appPlatform', 'appCategory', 'app_popularity', 'is_pref_cat']

In [5]:
y = dataset['label'].values

In [7]:
del dataset['label']

In [8]:
dataset.head()

,sitesetID,positionType,connectionType,telecomsOperator,hour,hour_weight,age,gender,education,marriageStatus,haveBaby,hometown,residence,user_activity,cat_pref,advertiserID,appPlatform,appCategory,app_popularity,is_pref_cat
0,0,3,1,1,0,225349,3,2,1,3,1,0,0,2.0,301.0,10,1,108,2.0,False
1,0,3,0,2,0,225349,3,2,2,0,1,13,0,2.0,407.0,10,1,108,2.0,False
2,0,3,0,3,0,225349,4,2,0,0,5,0,0,5.0,0.0,10,1,108,2.0,False
3,0,3,1,1,0,225349,3,1,1,0,0,0,0,2.0,104.0,10,1,108,2.0,False
4,0,3,1,1,0,225349,3,1,0,1,0,13,0,5.0,0.0,10,1,108,2.0,False

### testset_ol

In [3]:
testset_ol = pd.read_hdf(path_intermediate_dataset + 'testset_ol.h5')
testset_ol.head()

,instanceID,label,sitesetID,positionType,connectionType,telecomsOperator,hour,hour_weight,age,gender,...,haveBaby,hometown,residence,user_activity,cat_pref,advertiserID,appPlatform,appCategory,app_popularity,is_pref_cat
0,1,-1,0,1,1,3,0,225349,4,2,...,1,6,0,2.0,503.0,80,2,2,6.0,False
1,178,-1,0,1,1,2,0,225349,1,2,...,1,9,0,5.0,0.0,80,2,2,6.0,False
2,21839,-1,0,1,1,1,5,54638,3,2,...,1,6,0,5.0,0.0,80,2,2,6.0,False
3,25947,-1,0,1,1,3,6,88673,3,2,...,0,3,0,5.0,0.0,80,2,2,6.0,False
4,26757,-1,0,1,1,3,6,88673,4,2,...,0,0,0,5.0,0.0,80,2,2,6.0,False